version: 1.0.0-CI.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
environment:
  PROGET_API_KEY:
    secure: cK5vivAu043l5udO8/xlrju1zldGzrHfQxWXVNeyAfg=
install:
- ps: |
        nuget sources add -Name InedoExternalBuild -Source https://proget.inedo.com/nuget/ExternalBuild

        $currentVersion = [System.Version]::Parse((git grep -Fh '[assembly: AssemblyVersion("').Split('"')[1])

        $lastVersion = (ConvertFrom-Json (Invoke-WebRequest https://proget.inedo.com/upack/Extensions/packages?group=inedox).Content) | Where-Object name -eq $env:EXTENSION_NAME | ForEach-Object latestVersion

        if ($lastReleasedVersion -ne $null) {
          $lastVersion = [System.Version]::Parse($lastReleasedVersion)
          $nextVersion = [System.Version]::new($lastVersion.Major, $lastVersion.Minor, $lastVersion.Build + 1)
          if ($nextVersion -gt $currentVersion) {
            $currentVersion = $nextVersion
          }
        }

        Set-AppveyorBuildVariable EXTENSION_VERSION $currentVersion.ToString(3)

        Update-AppveyorBuild -Version ($currentVersion.ToString(3) + '-CI.' + $env:APPVEYOR_BUILD_NUMBER)
before_build:
-ps: nuget restore "$($env:EXTENSION_NAME)\$($env:EXTENSION_NAME).sln"
build:
  verbosity: minimal
after_build:
- ps: |
        $toolPath = "$($env:USERPROFILE)\inedoxpack.zip"

        (New-Object Net.WebClient).DownloadFile('https://s3.amazonaws.com/cdn.inedo.com/tools/inedoxpack.zip', $toolPath)

        Expand-Archive -Path $toolPath -DestinationPath .\Tools\inedoxpack

        .\Tools\inedoxpack\inedoxpack.exe ".\$($env:EXTENSION_NAME)\InedoExtension\bin\Release\$($env:EXTENSION_NAME).dll" ".\$($env:EXTENSION_NAME).upack"
artifacts:
- path: $(EXTENSION_NAME).upack
deploy_script:
- ps: |
        Invoke-RestMethod -Method Put `
          -Uri ('https://proget.inedo.com/upack/Appveyor/upload?version=' + $env:APPVEYOR_BUILD_VERSION) `
          -ContentType 'application/zip' `
          -InFile ('.' + $env:EXTENSION_NAME + '.upack') `
          -Headers @{ 'X-ApiKey' = $($env:PROGET_API_KEY) }
